[theme]
primaryColor = "#C41230"
backgroundColor = "#1a1a1a"
secondaryBackgroundColor = "#111111"
textColor = "#C8C8C8"
font = "sans serif"

[server]
maxUploadSize = 200
headless = true
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false
